---
title: "p8105_hw5_kq2127"
author: "Kristal Quispe"
date: "11/6/2019"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Problem 1

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

```


Writting the Function
```{r}
replace_na = function(x) {
  if (is.numeric(x)) {
    x[is.na(x)] = round(mean(x, na.rm = TRUE),1)
    x }
  else if (is.character(x)) {
    x[is.na(x)] = "virginica"
    x
  }
}
```


Testing the function
```{r}
replace_na(iris_with_missing[[1]])
replace_na(iris_with_missing[[2]])
replace_na(iris_with_missing[[3]])
replace_na(iris_with_missing[[4]])
replace_na(iris_with_missing[[5]])
```

Applying the function and mapping
```{r}
output = map_dfr(iris_with_missing, replace_na)

output
```

# Problem 2

```{r}
pb2_df = 
  list.files(
    path = "./data/",
    pattern = "*.csv",
    full.names = TRUE) %>% 
  map_df(read_csv, .id = "input") %>% 
  rename(id = input) %>% 
  mutate(
    id = as.numeric(id),
    arm = ifelse(id <= 10, "con", "exp"),
    id = recode(id,
       '11' = 1,
       '12' = 2,
       '13' = 3,
       '14' = 4,
       '15' = 5,
       '16' = 6,
       '17' = 7,
       '18' = 8,
       '19' = 9,
       '20' = 10)) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "observation") %>%
  select(id, arm, everything())

pb2_df %>% 
  mutate (id = as.factor(id)) %>% 
  ggplot(aes(x = week, y = observation, color = id, group = id)) + 
  geom_point(alpha =.5) +
  geom_line() +
  facet_grid(~arm) +
  ggtitle("Observations over time") 


```
Over time, the control arm tends to have an overall constant trend: there are dips and rises in observation values over time that mostly average out. On the other hand the experimental arm tends to increase in its observations values over time. 


# Problem 3



```{r}
set.seed(1)

sim_regression = function(n = 30, beta0 = 2, beta1) {
  
  sim_data = tibble(
    x = rnorm(n = 30),
    y = 2 + beta1 * x + rnorm(n = 30, 0, 50)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  
   pb3_df = tibble(
    beta1_hat = broom::tidy(ls_fit)[2, 2] %>% pull(),
    p = broom::tidy(ls_fit)[2, 5] %>% pull ()
  )
print(pb3_df)
}

```


```{r}
sim_regression(beta1 = 0)
```




```{r}
output = 
  rerun(10, sim_regression(beta1 = 0 )) %>% 
  bind_rows()

#10000 was on the verge of crashing my computer so I could only run 100. 

```




```{r}
#n_list = list("b1_1" = 1, 
#              "b1_2" = 2, 
#              "b1_3" = 3, 
#              "b1_4" = 4,
#              "b1_5" = 5,
#              "b1_6" = 6,)
#output = vector("list", length = 6)

#for (i in 1:6) {
#  output[[i]] = rerun(100, sim_regression(n_list[[i]])) %>% 
#    bind_rows
#}


```


